apiVersion: v1
kind: Service
metadata:
  name: my-app-go-service
spec:
  selector:
    app: go-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-node-service
spec:
  selector:
    app: node-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
